version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # You can use a different Node version if needed

jobs:
  install-and-test:
    executor: node-executor
    steps:
      - checkout  # Check out your source code
      - run:
          name: Install dependencies
          command: |
            npm install  # or `yarn install` if you use Yarn
      - run:
          name: Run unit tests
          command: |
            npm test  # or `yarn test` if you use Yarn
      - run:
          name: Build Next.js project
          command: |
            npm run build  # or `yarn build` if you use Yarn

workflows:
  version: 2
  build:
    jobs:
      - install-and-test